### ISSUE TITLE
Can open atom based tablet's webcam

### ISSUE THREAD

**Issue by fanfleto** [frankpapenmeier/webcam-capture-driver-native#2]
Hi Frank, thank you for your work.

I'm trying to open webcam of atom based tablets with javacv sarxos driver, but he has not implement open webcam with HD resolution.

This driver can to open atom based wabcam in HD resolution?

Thank you very much.

**Comment by frankpapenmeier** [comment]
Hi fanfleto,
I have not tested it on atom based Windows tablets, yet. However, I am confident that this could work. So it would be great if you could give it a try and report back. Opening HD webcam streams on Intel based Windows tablets works without problems.
All the best,
Frank.

**Comment by frankpapenmeier** [comment]
Hi fanfleto,
I just checked the Windows tablet that I developed this project on: Yes, it was also an atom based tablet. Therefore: Yes, this driver can open HD resolution webcams on atom based tablets.
All the best,
Frank.
