### ISSUE TITLE
Failed to load JNI backend

### ISSUE THREAD

**Issue by ReChab** [frankpapenmeier/webcam-capture-driver-native#3]
Hi Frank, thank you a lot for this work!
I am trying to use a IDS Ueye XS camera with the sarxos library, and your driver seems to be the key to get the good resolution from it.
However, when I try to do:

_Webcam.setDriver(new NativeWebcamDriver());_

(In aminimal test program in Netbean 7.3) I get:

_Exception in thread "main" com.github.sarxos.webcam.WebcamException: NativeWebcamDriver: Failed to load JNI backend
    at com.github.sarxos.webcam.ds.nativeapi.NativeWebcamDriver.<init>(NativeWebcamDriver.java:64)
    at testcameraueyexs_01.TestCameraUeyeXS_01.main(TestCameraUeyeXS_01.java:39)
Java Result: 1_

I suppose that Java cannot find webcam-capture-driver-native-64.dll
I tried to put it in my "working directory" and to set -Djava like you said, but I don't manage to have it working. Do you have any hint, idea or precisions about that?

**Comment by ReChab** [comment]
Some precision: I am working on windows 7 64bits. Netbeans and jdk1.7 are also 64bits.

Now, if I try to load the .dll directly:

_System.load("D:/05_processing3/03_Communication_Ueye_XS/webcam-capture-driver-native-64.dll");_

It says:

_java.lang.UnsatisfiedLinkError: D:\05_processing3\03_Communication_Ueye_XS\webcam-capture-driver-native-64.dll: %1 n’est pas une application Win32 valide_

(in french: "is not a valid Win32 application")

If I try to load the webcam-capture-driver-native-32.dll, it also says it is not a valid Win32 application.
I would appreciate your opinion a lot!

**Comment by frankpapenmeier** [comment]
Hi ReChab,

I never tried using the driver under Windows 7. It was developed and tested under Windows 10. This might explain your "is not a valid Win32 application" error. Possibly, I have built a dll that is not downward compatible to Windows 7.

Could you try to build the library yourself using the instructions that I gave under "How to build"? I would be interested to hear whether this works under Windows 7 and whether this gives you a respective dll that is compatible with your system.

Frank.

**Comment by ReChab** [comment]
Hi, thanks, I will try directly on a win 10 computer tomorrow then.
I managed to build the library on win 7 (I'm not used to doing this, so it took me quite a long time to have visual studio and cmake working together).
It seems to work, at least the library can be loaded now! But I need to test a bit further... I keep you informed.
Best regards
Renaud

**Comment by frankpapenmeier** [comment]
Thanks, looking forward to your results. Unfortunately, I am short on time at the moment such that I cannot directly support you with this at the moment.

**Comment by jlbrandt23** [comment]
Same error here, developing on a Windows 10 machine, JDeveloper IDE.

> Exception in thread "main" com.github.sarxos.webcam.WebcamException: NativeWebcamDriver: Failed to load JNI backend
> 	at com.github.sarxos.webcam.ds.nativeapi.NativeWebcamDriver.<init>(NativeWebcamDriver.java:64)
> 	at client.ErrorCase.<init>(ErrorCase.java:29)

**Comment by frankpapenmeier** [comment]
Hi jlbrandt23, I have not yet worked with JDeveloper, but this sounds like a typical *.dll file not found error. Please add the *.dll files to your java.library.path ... if you cannot find the setting, then please write me another message and I will have a look at JDeveloper.

**Comment by jlbrandt23** [comment]
Thanks - I got it working.  I'm not familiar with using .dll's and having to set the java.library.path.  My problem was I was setting the java.library.path to the .dll directory itself, instead of just to the directory the .dll resided in.

**Comment by frankpapenmeier** [comment]
@jlbrandt23 Thanks for the feedback and good to hear that you got it working.
