### ISSUE TITLE
use bridj instead of jni

### ISSUE THREAD

**Issue by snimavat** [frankpapenmeier/webcam-capture-driver-native#4]
Wouldnt it be good if the driver used bridj as used by saraxos capture project, rather thn doing JNI ?

**Comment by frankpapenmeier** [comment]
Hi @snimavat, I did some tests with JNA and bridj, but they did not succeed. Using JNI, this driver can directly compile against the cross-platform [video_capture](https://github.com/roxlu/video_capture) library for accessing the webcam buffer and the [libyuv]( https://chromium.googlesource.com/libyuv/libyuv) library for efficiently converting the varying capture formats of different webcam devices to ARGB images with acceptable strain on CPU resources. I am no bridj expert and thus do not know how all of this could be achieved with bridj only. If you feel comfortable with bridj and have ideas on how this could be achieved, I would love to see you working on this.
